name = "polyalpha"
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "polyalpha-db"
database_id = "aecafc19-f80e-49d4-a654-ca205ed69fe8"
